'use client'

import * as React from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Button, Input, Label, makeStyles, MessageBar, MessageBarBody } from '@fluentui/react-components'
import { ShieldCheckmark24Regular, Mail24Regular, LockClosed24Regular, Eye24Regular, ArrowRight24Regular } from '@fluentui/react-icons'
import { createClient } from '@/lib/supabase/client'

const useStyles = makeStyles({ page: { minHeight: '100vh', display: 'grid', placeItems: 'center', padding: '32px 20px', backgroundColor: '#f7f8fc' }, card: { width: '100%', maxWidth: '430px', padding: '34px', borderRadius: '20px', backgroundColor: '#ffffff', border: '1px solid #e8ebf2', boxShadow: '0 20px 55px rgba(36,47,75,.12)', display: 'flex', flexDirection: 'column', gap: '18px' }, logo: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '9px', fontSize: '22px', fontWeight: 800, color: '#7041d5' }, title: { textAlign: 'center', fontSize: '30px', fontWeight: 800, color: '#182033' }, sub: { textAlign: 'center', color: '#70798b' }, field: { display: 'flex', flexDirection: 'column', gap: '7px' }, input: { width: '100%' }, footer: { textAlign: 'center', color: '#70798b', fontSize: '13px' }, link: { color: '#7041d5', fontWeight: 700 } })

export default function LoginPage() {
  const styles = useStyles(); const router = useRouter(); const [email, setEmail] = React.useState(''); const [password, setPassword] = React.useState(''); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState(''); const [show, setShow] = React.useState(false)
  const handleLogin = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); const supabase = createClient(); const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) { setError(authError.message.toLowerCase().includes('confirm') ? 'Please confirm your email before signing in.' : 'Invalid email or password.'); setLoading(false) } else { router.push('/') } }
  return <main className={styles.page}><form className={styles.card} onSubmit={handleLogin}><div className={styles.logo}><ShieldCheckmark24Regular />SageCapital</div><div><h1 className={styles.title}>Welcome Back</h1><p className={styles.sub}>Sign in to your SageCapital account</p></div><div className={styles.field}><Label htmlFor="email" style={{ color: '#364152' }}>Email</Label><Input id="email" type="email" required value={email} onChange={e => setEmail(e.target.value)} className={styles.input} contentBefore={<Mail24Regular />} /></div><div className={styles.field}><Label htmlFor="password" style={{ color: '#364152' }}>Password</Label><Input id="password" type={show ? 'text' : 'password'} required value={password} onChange={e => setPassword(e.target.value)} className={styles.input} contentBefore={<LockClosed24Regular />} contentAfter={<button type="button" aria-label="Toggle password visibility" onClick={() => setShow(!show)}><Eye24Regular /></button>} /></div>{error && <MessageBar intent="error"><MessageBarBody>{error}</MessageBarBody></MessageBar>}<Button type="submit" appearance="primary" size="large" icon={<ArrowRight24Regular />} disabled={loading}>{loading ? 'Signing in...' : 'Sign In'}</Button><div className={styles.footer}>Don&apos;t have an account? <Link href="/signup" className={styles.link}>Create Account</Link></div></form></main>
}
