'use client'

import * as React from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Button, Input, Label, makeStyles, MessageBar, MessageBarBody } from '@fluentui/react-components'
import { ShieldCheckmark24Regular, Mail24Regular, LockClosed24Regular, Eye24Regular, Person24Regular, ArrowRight24Regular } from '@fluentui/react-icons'
import { createClient } from '@/lib/supabase/client'

const useStyles = makeStyles({ page: { minHeight: '100vh', display: 'grid', placeItems: 'center', padding: '24px', background: 'linear-gradient(135deg,#241044 0%,#0b1731 100%)', color: '#fff' }, card: { width: '100%', maxWidth: '460px', padding: '34px', borderRadius: '24px', backgroundColor: 'rgba(255,255,255,.09)', border: '1px solid rgba(255,255,255,.16)', boxShadow: '0 24px 70px rgba(0,0,0,.3)', backdropFilter: 'blur(18px)', display: 'flex', flexDirection: 'column', gap: '16px' }, logo: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '9px', fontSize: '22px', fontWeight: 800, color: '#c4b5fd' }, title: { textAlign: 'center', fontSize: '29px', fontWeight: 800 }, sub: { textAlign: 'center', color: '#b6c2d5' }, field: { display: 'flex', flexDirection: 'column', gap: '7px' }, input: { width: '100%', backgroundColor: 'rgba(255,255,255,.1)', border: '1px solid rgba(255,255,255,.2)', color: '#fff' }, footer: { textAlign: 'center', color: '#b6c2d5', fontSize: '13px' }, link: { color: '#c4b5fd', fontWeight: 700 } })

export default function SignupPage() {
  const styles = useStyles(); const router = useRouter(); const [form, setForm] = React.useState({ name: '', email: '', password: '', referral: '' }); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState(''); const [show, setShow] = React.useState(false)
  const handleSignup = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); const supabase = createClient(); const { error: authError } = await supabase.auth.signUp({ email: form.email, password: form.password, options: { data: { full_name: form.name, referral_code: form.referral } } }); if (authError) { setError(authError.message); setLoading(false) } else { router.push('/dashboard') } }
  return <main className={styles.page}><form className={styles.card} onSubmit={handleSignup}><div className={styles.logo}><ShieldCheckmark24Regular />SageCapital</div><div><h1 className={styles.title}>Create Your Account</h1><p className={styles.sub}>Join SageCapital investors earning weekly crypto returns</p></div><div className={styles.field}><Label htmlFor="name" style={{ color: '#e2e8f0' }}>Full Name</Label><Input id="name" required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className={styles.input} contentBefore={<Person24Regular />} /></div><div className={styles.field}><Label htmlFor="email" style={{ color: '#e2e8f0' }}>Email Address</Label><Input id="email" type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className={styles.input} contentBefore={<Mail24Regular />} /></div><div className={styles.field}><Label htmlFor="password" style={{ color: '#e2e8f0' }}>Password</Label><Input id="password" type={show ? 'text' : 'password'} required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className={styles.input} contentBefore={<LockClosed24Regular />} contentAfter={<button type="button" aria-label="Toggle password visibility" onClick={() => setShow(!show)}><Eye24Regular /></button>} /></div><div className={styles.field}><Label htmlFor="referral" style={{ color: '#e2e8f0' }}>Referral Code (optional)</Label><Input id="referral" value={form.referral} onChange={e => setForm({ ...form, referral: e.target.value })} className={styles.input} /></div>{error && <MessageBar intent="error"><MessageBarBody>{error}</MessageBarBody></MessageBar>}<Button type="submit" appearance="primary" size="large" icon={<ArrowRight24Regular />} disabled={loading}>{loading ? 'Creating account...' : 'Create Account'}</Button><div className={styles.footer}>Already have an account? <Link href="/login" className={styles.link}>Sign In</Link></div></form></main>
}
